name: Publish to NPM and GPR

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js for NPM
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://registry.npmjs.org/'

      - name: Publish package to NPM
        run: npm publish --access public --@rpgtec:registry=https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Set up Node.js for GPR
        uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com/'

      - name: Publish package to GPR
        run: npm publish --access public --@rpgtec:registry=https://npm.pkg.github.com
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
